version: "3.3"

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: electric
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "54321:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - db-tmp:/tmp
    command:
      - -c
      - listen_addresses=*
      - -c
      - wal_level=logical

  electric:
    image: electricsql/electric:1.0.0-beta.8
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/electric?sslmode=disable
      # DATABASE_URL: postgresql://neondb_owner:npg_QYRhFk8zT4qX@ep-young-wave-a9eifju3.gwc.azure.neon.tech/neondb?sslmode=require
    ports:
      - "3100:3000"
    depends_on:
      - postgres

volumes:
  db-data:
  db-tmp: